### ISSUE TITLE
NAudio.MmException: BadDeviceId calling waveInOpen

### ISSUE THREAD

**Issue by rhaley-starfish** [lextrack/Simple-Screen-Recorder#13]
Hi,

I get a "NAudio.MmException: BadDeviceId calling waveInOpen" error if the "audio recording method" includes a microphone option and no microphone is connected. The recording works fine if I select "System audio only".

I tried going back to 1.20 and the error is still present.

**Comment by lextrack** [comment]
The bug was fixed. This used to happen when you launch the app with no mic connected to your PC. Now the user will get an error message and the speaker audio will be recorded instead.
![Screenshot 2024-01-01 222022](https://github.com/lextrack/Simple-Screen-Recorder/assets/42826936/a12bc8fd-44cc-4aaa-a59d-306c2c20bb04)
